version: '3.7'

services:
  sociallogin.backend:
    build: ./BACKEND
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    environment:
      - is_prod=False
    develop:
      watch:
        - action: rebuild
          path: ./BACKEND

    

      
  sociallogin.frontend:
    build: 
      context: ./FRONTEND
      target: develop
    container_name: frontend

    expose: 
      - 9000

    develop:
      watch:
        - action: rebuild
          path: ./FRONTEND 


    entrypoint: /bin/sh -c "quasar dev -p 9000"
  
  proxy:
    build: 
      context: ./PROXY
      target: dev
    container_name: proxy
    ports:
      - "80:80"
    develop:
      watch:
        - action: rebuild
          path: PROXY/
