version: '3.7'

services:
  sociallogin.backend:
    build: 
      context: ./BACKEND
    container_name: backend
    command: gunicorn -b 0.0.0.0:8000 sociallogin.wsgi
    volumes:
      - static_volume:/static
    expose:
      - "8000"
    environment:
      - is_prod=True
      - POSTGRES_NAME=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=
      - SECRET_KEY=
    develop:
      watch:
        - action: rebuild
          path: ./BACKEND
    

      
  sociallogin.frontend:
    build: 
      context: ./FRONTEND
      target: prod
    container_name: frontend
    # image: sociallogin.frontend:v0.1

    expose:
      - 80

    develop:
      watch:
        - action: rebuild
          path: ./FRONTEND

    entrypoint: ["nginx", "-g", "daemon off;"]

  proxy:
    build: PROXY
    container_name: proxy
    volumes:
      - static_volume:/static
    ports:
      - "80:80"
    develop:
      watch:
        - action: rebuild
          path: PROXY/

volumes:
  static_volume:
