version: '3.7'

services:
  backend:
    container_name: backend
    image: ghcr.io/alvarohc777/sociallogin.backend:v1.0
    command: gunicorn -b 0.0.0.0:8000 sociallogin.wsgi 
    volumes:
      - static_volume:/static
    expose:
      - "8000"
    environment:
      - is_prod=True
      - ALLOWED_HOSTS=
      - CORS_ALLOWED_ORIGINS=
      - FRONTEND_URL=
      - CSRF_TRUSTED_ORIGINS=
      - POSTGRES_NAME=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=
      - POSTGRES_PORT=
      - ACCOUNT_DEFAULT_HTTP_PROTOCOL=https
      - SECRET_KEY=
    networks:
      - mynetwork

  frontend:
    container_name: frontend
    image: ghcr.io/alvarohc777/sociallogin.frontend:v1.0
    expose:
      - "80"
    entrypoint: ["nginx", "-g", "daemon off;"]
    networks:
      - mynetwork
    depends_on:
      - backend

  proxy:
    container_name: proxy
    image: ghcr.io/alvarohc777/sociallogin.proxy:v1.0
    volumes:
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  static_volume: